# This is a basic workflow to help you get started with Actions

name: x-dr

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: x-dr/sync-repo-to-gitee@master
      env:
          # 在 Settings->Secrets 配置 GITEE_KEY
          SSH_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          github-repo: "https://github.com/lukesampson/scoop.git"
          # 注意替换为你的 Gitee 目标仓库地址
          gitee-repo: "git@gitee.com:scoop-mirror/scoop.git"
  
